### ISSUE TITLE
Add 'Edit Preferences' functionality 

### ISSUE THREAD

**Issue by ark234** [ark234/FLYING-ORANGE#11]
USER STORY: as a user, I would like to be able to update my allergen/dietary preferences, so the search form is automatically pre-populated with desired checkboxes. 

FRONT END: need a view that displays a form (similar to home search form) in which user can select checkboxes indicating allergen/dietary preferences. Submitting the form should send PUT request to `http://localhost:8080/users/preferences` (or something like that) with updated health labels and user id inside its body. 

BACK END: need a controller to pick up requested route, and call middleware that will UPDATE user preferences inside profiles table.

**Comment by Wheaties247** [comment]
I can work on this

**Comment by Wheaties247** [comment]
I just Completed the sample code, i have not tested with results

**Comment by Wheaties247** [comment]
ISSUE COMPLETED
