### ISSUE TITLE
Add 'Edit Account' functionality

### ISSUE THREAD

**Issue by ark234** [ark234/FLYING-ORANGE#12]
USER STORY: as a user, I want to be able to edit my email and password.

FRONT END: need a view with pre-populated email and blank password fields. Upon submitting the form, it should send PUT request to `http://localhost:8080/users/account` (or something like that) with updated information inside its body. 

BACK END: need controller to pick up the route, and call middleware that will update the users table.

**Comment by Wheaties247** [comment]
Im working on this now
