### ISSUE TITLE
Add Nav component

### ISSUE THREAD

**Issue by ark234** [ark234/FLYING-ORANGE#6]
USER STORY: as a user, I want to have the option of using the app regardless of whether I am logged in or not. If I am not logged in, I want to have the option to navigate to Login or Register views. If I am logged in, I want to have the option to navigate to Saved Recipes, User Preferences, and Account Settings. 

FRONT END: There should be a single `Nav` component that conditionally renders `UserNav` if `this.state.isLoggedIn == true` or `GuestNav` if `this.state.isLoggedIn == false`. `UserNav` should have Links to Saved Recipes, User Preferences, Account Settings, and Logout. `GuestNav` should have Links to Login and Register. 

Don't worry about fleshing out each child component in Nav for now, dummy placeholders are fine.

**Comment by ark234** [comment]
@Wheaties247 added notes, let me know if this makes sense

**Comment by Wheaties247** [comment]
COMPLETE

**Comment by ark234** [comment]
@Wheaties247 there is a bug, if you try to navigate to sign up or login from results page, it throws the following error: 
```TypeError: _this2.props.toggleSignUp is not a function```

**Comment by Wheaties247** [comment]
Issue resolved
