### ISSUE TITLE
Add save recipe functionality

### ISSUE THREAD

**Issue by ark234** [ark234/FLYING-ORANGE#8]
USER STORY: As a user, I want to be able to save a recipe so I can easily find it later, without needing to perform a search. 

FRONT END: we need to add 'Save Recipe' button to our RecipeInfo component. The click handler should extract `user_id`, `uri`, `img_url`, `name`, and `health_label` from props and pass them into body of POST request to `http://localhost:8080/recipes/save` (or something like that). 

BACK END: we need to create model and controller components to process the `/recipes/save` route and save information to database. The query parameters should come from `req.body` of POST request described in paragraph above.

**Comment by ailavinda** [comment]
Acknowledged

**Comment by ark234** [comment]
@ailavinda just to clarify, to test functionality of saving user-saved recipes, you can manually INSERT user into the database and then hardcode `user_id` into your POST request. Once I finish the login we would be able to access `user_id` through props. Let me know if this makes sense.

**Comment by ark234** [comment]
Also, please only add 'Save Recipe' functionality, we will implement 'Delete' and 'Retrieve' later.

**Comment by Wheaties247** [comment]
i can work on this, does anyone see conflicts with me working on this issue
